apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP
  namespace: $NS
spec:
  replicas: $POD_NUM
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
      - name: $APP
        image: $IMAGE_URL
        ports:
        - containerPort: $PORT
          name: http
        readinessProbe:
          httpGet:
            path: $URI
            port: $PORT
        livenessProbe:
          httpGet:
            path: $URI
            port: $PORT
          initialDelaySeconds: 40
          periodSeconds: 30
        resources:
          requests:
            memory: $MEMORY
            cpu: $CPU
          limits:
            memory: $MEMORY
            cpu: $CPU
  imagePullSecrets:
  - name: $NS-reg
---
apiVersion: v1
kind:  Service
metadata:
  name: $APP
  namespace: $NS
spec:
  selector:
    app: $APP
  ports:
    - port: $PORT
      targetPort: $PORT
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: $APP-pvc
#  namespace: $NS
#spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: $PVC
#    limits:
#      storage: $PVC
